include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    inference_failure_on_instance_creation: ignore
    inference_failure_on_function_invocation: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"